env:
- NODE_ENV=test
language: node_js
node_js:
  - "7"
services:
  - mongodb
before_install:
  - npm install -g typescript@2.3.3
before_script:
  - sleep 15
  - mongo blogTestdb --eval 'db.addUser("root", "root");'